- honeybot/plugins/dadjoke.py
added plugin to get random "dad jokes" from icanhazdadjokes.com
> added dadjoke plugin

- CONTRIBUTING.md
- honeybot/main.py
- honeybot/run.py
created run.py file to replace main.py as starting point and changed CONTRIBUTING.md to contain the updated procedure for contributing
> created run.py file to run the bot 

- honeybot/plugins/mail.py
Removed code in mail.py that used file.read and string split to read values from email_config.conf file. Added code that uses configparser to do the same.
> added cofigparser

- honeybot/main.py
Added some comments to main -> very (very very) new to this so started basic, if want more let me know! Will work on Spinx setup over this week! Thanks for letting newbies try this all out!
> Comments added

- honeybot/plugins/repostats.py
> added repostats plugin

- honeybot/settings/PLUGINS.conf
Add pynews to PLUGINS.conf so that it will be accesible by default.
> Add pynews to PLUGINS.conf

- honeybot/manager.py
Created an MVP of the plugin manager GUI
> Plugin manager

- README.md
> added new plugin idea in to do

- honeybot/plugins/proverb.py
- honeybot/run.py
- honeybot/settings/CONNECT.conf.save
added proverb.py in the plugin folder
> added proverb plugin

- .gitignore
- honeybot/main.py
> update doc string in set_nick_command

- honeybot/main.py
Strings changed to  " .format " type.
> Added string formatting in main.py

- honeybot/main.py
Formatted the string on line 358 in main.py.
> formatted the forgotten string

- README.md
- honeybot/main.py
1. Changed return statement (issue #44 )
2. Also changed if-else statement in line 254 to one line expression
3. Updated "Updating fork" section in the README.md file. Changed ```git remote add upstream git://github.com/Abdur-rahmaanJ/honeybot.git``` to ```git remote add upstream https://github.com/pyhoneybot/honeybot.git``` and also some minor grammar fix
> Change if else statement

- README.md
I decided I was good and ready to actually put down my experience. Also it's really weird that github is giving me the notification spiel about how this is my first time opening a PR to this project. Wack.
> Finally added in my testemonial

- README.md
- docs/source/plugins.rst
- honeybot/plugins/magic_ball.py
- honeybot/settings/PLUGINS.conf
- Added A Magic 8 Ball plugin 
- Added the plugin to the plugin.rst file
- Added plugin to the list in the README.md file
> Added Magic 8 Ball plugin

- honeybot/plugins/random_color.py
I have added a plug which sends a message in a random color. It uses the standard 16 IRC colors. This is a pull request in response to issue #50.
> Added Random color message plugin

- honeybot/plugins/onthisday.py
- honeybot/plugins_info.md
- honeybot/settings/PLUGINS.conf
Hello
I am participating in my very first Hacktoberfest and I came across this bot. I thought it looked pretty cool and wanted to try my hand at creating a plugin.
I made a "on this day" plugin. Which will retrieve a fact about something that happened on this day.
Command .onthisday
Still new to contributing so please let me know if I made any mistakes or anything I can do to improve my contribution. 
Thank you.
> added on this day plugin

- honeybot/plugins/telephone_code.py
#63
Add all the countries with code and their country telephone code.
> Add telephone code for all the countries

- honeybot/plugins/story.py
Story plugin that prints a 2-3 IRC message story when prompted.
> PR for story.py 

- honeybot/plugins/random_color.py
- honeybot/settings/PLUGINS.conf
- fixed the indexing from the "info" parameter to properly get the command
- the command will now output HEX colour codes, also fixing the concatenation errors
- changed the command ".rancol" to ".randcol" (for consistency with .rand command)
- improved overall code style
- added plugin to PLUGINS.conf
> Changes to random_colour plugin

- README.md
- honeybot/plugins/corona.py
- honeybot/plugins/diary.py
- honeybot/plugins/flight.py
- honeybot/plugins/riddle.py
- honeybot/plugins_info.md
- honeybot/settings/OWNERS.conf
- honeybot/settings/PLUGINS.conf
- requirements.txt
I have added the following plugins:
- corona
it allows you to get information about the coronavirus outbreak
- diary
allows you to keep a diary on honeybot
- flight 
it allows you to get flight information by the callsign of a flight
i have encountered one bug and would like to request help in solving it
it appears to me that diary executes twice because it prints outputs twice but its not clear to me why.
> 3 new plugins

- honeybot/plugins/sysinfo.py
System Information Plugin has been added (sysinfo).
We have .botinfo to display all the available commands available to gain information about the bot host's system.
System Information: .sysinfo
Boot Information: .bootinfo
CPU Information: .cpuinfo
Memory Information: .memoryinfo
Disk Information: .diskinfo
Network Information: .networkinfo
> Added System Information Plugin

- README.md
Noticed some capitalisation errors in the README.md document.
> Capitalise letters at the start of a new sentence.

- honeybot/plugins/downloaded/book_of_day/info.py
Moved docstring to info.py as per issue #79
> Docstring moved to info.py

- honeybot/plugins/downloaded/age/info.py
- honeybot/plugins/downloaded/bitcoin/info.py
- honeybot/plugins/downloaded/blackjack/info.py
> Add docstring as info.py for blackjack, age, and bitcoin

- docs/source/How_Tos/documentation.rst
- honeybot/plugins/downloaded/fact/main.py
> 5 facts added

- honeybot/plugins/downloaded/fact/main.py
> Add last four facts to fact/main.py

- honeybot/plugins/downloaded/fact/main.py
> Fixed style

- honeybot/plugins/downloaded/fact/main.py
I had forgot to paste a few words that i removed from a fact
> Fixed error

- README.md
- docs/source/How_Tos/documentation.rst
- docs/source/Plugins/development.rst
- docs/source/Plugins/fun.rst
- docs/source/Plugins/miscellaneous.rst
- docs/source/Plugins/utility.rst
- docs/source/conf.py
- docs/source/main.rst
- src/honeybot/plugins/downloaded/book_of_day/main.py
- src/honeybot/plugins/downloaded/converter/main.py
- src/honeybot/plugins/downloaded/dadjoke/main.py
- src/honeybot/plugins/downloaded/news/main.py
- src/honeybot/plugins/downloaded/weather/main.py
Fixing Sphinx setup and some RST files.
> Fixing Sphinx setup and some RST files

- docs/source/How_Tos/documentation.rst
Updating documentation.rst to make it clearer and reflect the recent changes made.
>  - Updating documentation.rst to make it clearer

- src/honeybot/gui_manager.py
- Removing exec() vulnerable function
> Enhancement #3

- .github/workflows/githubci.yml
> Update bandit with plugins check

- setup.py
> fix typo setup.py

- README.md
First clean up step of the repository
- Improve readability and reorder to improve the end-user experience
> Clean up `README.md`

- src/honeybot/api/main.py
- src/honeybot/api/memory.py
- src/honeybot/api/print.py
- src/honeybot/manage.py
> Py3.10 compatibility

- src/honeybot/api/main.py
- src/honeybot/api/memory.py
Fix lint error messages on core api in files:
- memory
- main
> Fix lint error messages on core api

- .github/workflows/build.yml
- .github/workflows/githubci.yml
- README.md
- Rename the action to `build`
- Update `setup-python`
- Apply to all branches except `gh-pages`
- Fix whitespaces
- Add `master` branch badge
> Apply CI to all branches except `gh-pages`

- .pre-commit-config.yaml
Addition: Pre-commit validation \ formatting before new PRs
Fully tested at local repo
> Add: Pre-commit validation \ formatting before new PRs

- How_Tos/documentation.html
- _sources/How_Tos/documentation.rst.txt
Update the contributing guide - fine-tuning.
Local repo
> Documentation - update the contributing guide - fine tuning.

- README.md
- src/honeybot/plugins/downloaded/url_shorten/info.py
- src/honeybot/plugins/downloaded/url_shorten/main.py
- src/honeybot/plugins/downloaded/url_shorten/requirements.txt
Added new plugin for url shortener.
created local devenv and tested manually.
> added new plugin url-shortener.

- src/honeybot/plugins/core/joins/main.py
- src/honeybot/plugins/core/log/main.py
- src/honeybot/plugins/core/uptime/main.py
Issue #153
This PR fixes issue #153 by updating the run functions on Plugins joins, log, and uptime.
After the fixes, I reran the project and the errors were not happening anymore.
> Fix: Some plugins had wrong run signature

- src/honeybot/plugins/downloaded/duckduckgo/main.py
- src/honeybot/plugins/downloaded/url_shorten/main.py
- url_shorten/main.py
- duckduckgo/main.py
Fix linter format
Local repo
> Format new plugins to comply black rules:

- .github/workflows/scorecards.yml
> chore(actions): Update checkout version

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- src/honeybot/gui_manager.py
> chore: dummy pr

- Dockerfile
- README.md
Add docker run argument to separate honeybot init and run fazes 
On local docker image
- Fix the unnamed image problem
- Change the base image from python to ubuntu's latest
- [x ] I have updated the documentation accordingly
> Dockerfile adjustments

- docs/source/How_Tos/setup_bot.rst
- Update main documentation branch with new docker use info
Update main documentation branch with new docker use info
local repo
> Dockerfile adjusts:

- docs/source/How_Tos/contributing.rst
- docs/source/Plugins/fun.rst
- Updating Contributing guide
- Fixing IMDb Movies plugin erasure in way of use
Local repo
> Changed RST doc files:

- src/honeybot/api/commands.py
- src/honeybot/manage.py
> fix pr 196

- src/honeybot/api/main.py
- src/honeybot/api/print.py
> chore: improve output messages

- README.md
> chore: remove aviyel from readme

- src/honeybot/api/main.py
> chore: remove unaccessed function from botcore file

- README.md
> docs: update settings info
